### ISSUE TITLE
events implementation has changed

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [MisterPhilip/universal-analytics-migration#8]
take a look at this link: https://developers.google.com/analytics/devguides/collection/analyticsjs/events#implementation

Using your script, events are not recorded. It should be in this form:

```
ga('send', {
  hitType: 'event',
  eventCategory: 'Videos',
  eventAction: 'play',
  eventLabel: 'Fall Campaign'
});
```

**Comment by WhitWaldo** [comment]
@oguzhankahyaoglu Looking at that documentation, I'm not seeing how the original is incorrect or that this has been changed in some way. As it says on that page "as with all send commands, the fields passed in the convenience parameters may also be specified in the fieldsObject." 

Thus, using your example, you can use either:

`ga('send', 'event', 'Videos', 'play', 'Fall Campaign');`

or

`ga('send', {'hitType': 'event', 'eventCategory': 'Videos', 'eventAction': 'play', 'eventLabel': 'Fall Campaign'});`

Within GA, there's functionally no difference between the two - it'll take either one. 

@MisterPhilip I don't see that a change is necessary here.

**Comment by MisterPhilip** [comment]
Yup, either way here is correct! No change is required.
